package authTest;

import java.io.*;
import java.security.*;

/*
diffie hellman
g : small prime
n : 2000 bit number

a : private large number between 1..n
b : private large number between 1..n

(g^a) mod n : alice's public msg to bob
(g^b) mod n : bob's public msg to alice

(g^b) mod n ^ a : alice's shared secret
(g^a) mod n ^ b : bob's shared secret
 */
/*
Alice and the server knows each other’s public key
Alice challenges the server with number X
Server signs X with its PRIVATE key, and sends back the signature
Alice verifies the signature using the server’s PUBLIC key
The same process applies when Server challenges Alice
 */
/*
Alice initiates a connection to the Server
SERVER challenges Alice by sending number X
Alice encrypts the challenge + her identifier using her key, and sends back the cipher text
Cipher text contains Alice’s username + challenge
You can image you have an object that consists of two data fields: username and challenge, you encrypt this object and send back a sealed object
In real world, the identifier is often the IP address of the party
SERVER decrypts the cipher text
If the message is generated by Alice (i.e. username == Alice), accepts it
If the message is generated by the SERVER in the past, rejects it.
 */
public class KeyGen {
  public static void main(String[] args) throws Exception{
//    KeyPairGenerator keyGen = KeyPairGenerator.getInstance("DSA");
//    keyGen.initialize(1024, SecureRandom.getInstance("SHA1PRNG"));
//    KeyPair pair = keyGen.generateKeyPair();
//    PrivateKey priv = pair.getPrivate();
//    PublicKey pub = pair.getPublic();
//
//    saveSerializedFile("publicKeyS", pub);
//    saveSerializedFile("privateKeyS", priv);

    System.out.println((1252 / 100f));
  }

  /**
   * Returns the collection of Actors for the scene.
   *
   * @return A collection of all Actor objects within the scene
   */
  static Object loadSerializedFile(String fileName) {
    Object result = null;
    try (
        FileInputStream fileIn = new FileInputStream(fileName + ".ser");
        ObjectInputStream objIn = new ObjectInputStream(fileIn)) {
      result = objIn.readObject();
    } catch (ClassNotFoundException | IOException ex) {
      ex.printStackTrace();
      System.exit(1);
    }

    return result;
  }

  /**
   * Saves the current collection of actors to a binary file.
   */
  static void saveSerializedFile(String fileName, Object toSave) {
    try (
        FileOutputStream fileOut = new FileOutputStream(fileName + ".ser");
        ObjectOutputStream objOut = new ObjectOutputStream(fileOut)) {
      objOut.writeObject(toSave);
    } catch (IOException ex) {
      ex.printStackTrace();
      System.exit(1);
    }
  }
}
